<a href="https://colab.research.google.com/github/pascalwilman28/developer-pascalwilman28/blob/master/ANN_%26_SVM_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Support Vector Machine

In [70]:
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

X = np.array([[1, 0, 1, 0, 0, 0],
     [1, 0, 1, 1, 0, 0],
     [1, 0, 1, 0, 1, 0],
     [1, 1, 0, 0, 1, 1],
     [1, 1, 1, 1, 0, 0],
     [1, 0, 0, 0, 1, 1],
     [1, 0, 0, 0, 1, 0],
     [0, 1, 1, 1, 0, 1],
     [0, 1, 1, 0, 1, 1],
     [0, 0, 0, 1, 1, 0],
     [0, 1, 0, 1, 0, 1],
     [0, 0, 0, 1, 0, 1],
     [0, 1, 1, 0, 1, 1],
     [0, 1, 1, 1, 0, 0]])
y =  np.array([1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0])

from sklearn.svm import SVC
clfsvm = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clfsvm.fit(X, y)


Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svc',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape='ovr', degree=3,
                     gamma='auto', kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)

In [74]:
print(clfsvm.predict([[1, 0, 1, 1, 0, 0]]))

[1]


In [75]:
print(clfsvm.predict([[0, 1, 1, 1, 0, 0]]))

[0]


In [76]:
clfsvm[1]

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [77]:
clfsvm[1].support_vectors_

array([[ 1.        , -1.        , -1.15470054, -1.        ,  1.        ,
        -1.        ],
       [-1.        ,  1.        ,  0.8660254 , -1.        ,  1.        ,
         1.        ],
       [-1.        , -1.        , -1.15470054,  1.        ,  1.        ,
        -1.        ],
       [-1.        ,  1.        , -1.15470054,  1.        , -1.        ,
         1.        ],
       [-1.        , -1.        , -1.15470054,  1.        , -1.        ,
         1.        ],
       [-1.        ,  1.        ,  0.8660254 , -1.        ,  1.        ,
         1.        ],
       [-1.        ,  1.        ,  0.8660254 ,  1.        , -1.        ,
        -1.        ],
       [ 1.        , -1.        ,  0.8660254 , -1.        , -1.        ,
        -1.        ],
       [ 1.        , -1.        ,  0.8660254 ,  1.        , -1.        ,
        -1.        ],
       [ 1.        , -1.        ,  0.8660254 , -1.        ,  1.        ,
        -1.        ],
       [ 1.        ,  1.        , -1.15470054, -1.

ANN


In [66]:
from sklearn.neural_network import MLPClassifier
X = [[1, 0, 1, 0, 0, 0],
     [1, 0, 1, 1, 0, 0],
     [1, 0, 1, 0, 1, 0],
     [1, 1, 0, 0, 1, 1],
     [1, 1, 1, 1, 0, 0],
     [1, 0, 0, 0, 1, 1],
     [1, 0, 0, 0, 1, 0],
     [0, 1, 1, 1, 0, 1],
     [0, 1, 1, 0, 1, 1],
     [0, 0, 0, 1, 1, 0],
     [0, 1, 0, 1, 0, 1],
     [0, 0, 0, 1, 0, 1],
     [0, 1, 1, 0, 1, 1],
     [0, 1, 1, 1, 0, 0]]
y =   [1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5,2), random_state=1)
clf.fit(X, y)


MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(5, 2), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=1, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [67]:
clf.coefs_

[array([[-0.43993892,  6.38131842, -7.33242495, -1.07051941,  1.39840273],
        [-0.91430863, -2.10004857,  0.3445903 , -1.25726857, -3.05629343],
        [-0.97226313, -0.99276157, -3.20663788, -1.35990249, -2.62330674],
        [ 0.5193766 ,  1.84072557,  0.73638444, -0.52983184, -3.6027074 ],
        [ 0.78301666, -1.52644828,  5.62674327, -1.58901954, -0.02654873],
        [ 0.74932499, -1.72331067, -3.1796509 , -1.59162371, -2.88561488]]),
 array([[-0.16232727,  1.0383646 ],
        [-0.12914399, -3.4774781 ],
        [ 3.21482824,  2.98251894],
        [-0.54437384, -0.23421022],
        [ 0.93299858,  0.85614299]]),
 array([[-2.48157976],
        [-5.85999031]])]